version: '3'


## Setting up services : NGINX, MARIADB, WORDPRESS
services:
    nginx:
        image:  nginx
        container_name: nginx
        restart:  unless-stppped
        ports:
          - 443:443
        build: requirements/nginx
        env_file: .env
        volumes:
            - wordpress:/var/www/html
        networks:
            - inception
        depends_on :
            - wordpress


    mariadb:
        image:  mariadb
        container_name: mariadb
        restart:    unless-stopped
        ports:
            - "3306"
        build: requirements/mariadb
        env_file: .env
        volumes:
            - mariadb:/var/lib/mysql


    wordpress:
        image:  wordpress
        container_name: wordpress
        restart:    unless-stopped
        ports:
            - "9000"
        build: requirements/wordpress
        env_file: .env
        volumes:
            - wordpress:/var/www/html
        networks:
            - inception
        depends_on :
            - mariadb

## Setting up Network
networks:
    inception:
        driver: bridge

## Setting up Volumes : MARIADB, WORDPRESS
volumes:
    mariadb:
        driver: local
        driver_opts: 
            type: 'none'
            o: 'bind'
            device: '/home/julpelle/data/mariadb'
    wordpress:
        driver: local
        driver_opts: 
            type: 'none'
            o: 'bind'
            device: '/home/julpelle/data/wordpress'
    