version: "3"

services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    ports:
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - wp_files:/var/www/html
    networks:
      - inception
    restart: on-failure

  wordpress:
    build: ./requirements/wordpress/
    container_name: php-fpm
    depends_on:
      - mariadb
    ports:
      - 127.0.0.1:9000:9000
    volumes:
      - wp_files:/var/www/html
    env_file:
      - ./.env
    networks:
      - inception
    restart: on-failure

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - db_files:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - inception
    restart: on-failure

networks:
  inception:

volumes:
  wp_files:
    driver: local
    driver_opts:
      type: none
      device: /home/elaachac/data/wp_files
      o: bind
  db_files:
    driver: local
    driver_opts:
      type: none
      device: /home/elaachac/data/db_files
      o: bind